pub const LXSS_HANDLE_USE_CONSOLE: u32 = 0;

pub const LXSS_DISTRO_FLAGS_ENABLE_INTEROP: u32 = 0x1;
pub const LXSS_DISTRO_FLAGS_APPEND_NT_PATH: u32 = 0x2;
pub const LXSS_DISTRO_FLAGS_ENABLE_DRIVE_MOUNTING: u32 = 0x4;
pub const LXSS_DISTRO_FLAGS_VM_MODE: u32 = 0x8;
pub const LXSS_DISTRO_FLAGS_WSLCORE_MODE: u32 = 0x10;

pub const LXSS_ENUMERATE_FLAGS_DEFAULT: u32 = 0x1;

pub const LXSS_GET_DISTRO_ID_LIST_ALL: u32 = 0x1;

pub const LXSS_CREATE_INSTANCE_FLAGS_ALLOW_FS_UPGRADE: u32 = 0x1;
pub const LXSS_CREATE_INSTANCE_FLAGS_OPEN_EXISTING: u32 = 0x2;
pub const LXSS_CREATE_INSTANCE_FLAGS_IGNORE_CLIENT: u32 = 0x4;
pub const LXSS_CREATE_INSTANCE_FLAGS_USE_SYSTEM_DISTRO: u32 = 0x8;
pub const LXSS_CREATE_INSTANCE_FLAGS_SHELL_LOGIN: u32 = 0x10;

pub const LXSS_EXPORT_DISTRO_FLAGS_VHD: u32 = 0x1;
pub const LXSS_EXPORT_DISTRO_FLAGS_GZIP: u32 = 0x2;
pub const LXSS_EXPORT_DISTRO_FLAGS_XZIP: u32 = 0x4;
pub const LXSS_EXPORT_DISTRO_FLAGS_VERBOSE: u32 = 0x8;

pub const LXSS_IMPORT_DISTRO_FLAGS_VHD: u32 = 0x1;
pub const LXSS_IMPORT_DISTRO_FLAGS_CREATE_SHORTCUT: u32 = 0x2;
pub const LXSS_IMPORT_DISTRO_FLAGS_NO_OOBE: u32 = 0x4;
pub const LXSS_IMPORT_DISTRO_FLAGS_FIXED_VHD: u32 = 0x8;

pub const LXSS_ATTACH_MOUNT_FLAGS_PASS_THROUGH: u32 = 0x1;
pub const LXSS_ATTACH_MOUNT_FLAGS_VHD: u32 = 0x2;
