name: Test WSL API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        wsl-version: [1, 2]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        
    - name: Enable WSL
      uses: Vampire/setup-wsl@v6
      with:
        wsl-version: ${{ matrix.wsl-version }}

    - name: Run basic usage example
      run: |
        cargo run --example basic_usage
        
    - name: Run tests
      run: |
        # Run tests to ensure everything compiles correctly
        cargo test --workspace
        
    - name: Check compilation
      run: |
        # Ensure everything compiles without warnings
        cargo check --workspace 
